#!/usr/bin/python3
def safe_function(fct, *args):
    try:
        return (fct(*args))
    except Exception as ex:
        print("Exception: {}".format(ex))
        return (None)
